export const EMOTIONS = {
  "😊": "😊 Happiness",
  "😂": "😂 Laughter",
  "😍": "😍 Love",
  "🥺": "🥺 Affection",
  "😢": "😢 Sadness",
  "😡": "😡 Anger",
  "😨": "😨 Fear",
  "😟": "😟 Concern",
  "😲": "😲 Shock",
  "😀": "😀 Elation",
};

export const TRAITS = {
  "😍": "😍 Love Potential",
  "💫": "💫 Destiny Factor",
  "🤝": "🤝 Trustworthiness",
  "🤔": "🤔 Intellectual Quotient",
  "📞": "📞 Communication Style",
  "😂": "😂 Humor Level",
  "🎵": "🎵 Musicality",
  "🌍": "🌍 Adventurousness",
  "🎁": "🎁 Gift-Giving Prowess",
  "💃": "💃 Dance Aptitude",
  "🍽": "🍽 Culinary Skills",
  "⭐": "⭐ Cosmic Significance",
  "👥": "👥 Respectfulness",
  "🎨": "🎨 Creative Spirit",
  "🧠": "🧠 Interest Breadth",
};
